# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5809b319c1b6f55fcc91ba9f11deebc838f4d013587614baac982d135370261f107b0c2f4ebb9de9c650320b3375f9cb52a75821d1d26969f1c2479b2d4268bf

test:
  secret_key_base: dae468e477c980294b6c283002594044e96072ea7271b997c6638e4165bccf23db4632b7a23f1b83f560fad8d6eda7c5f0f6e7c2a7b4754ca701bdc4b2f66f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: dae468e477c980294b6c283002594544a96071ea7241b697c6638e4165bccf23db4632b7a23f1b83f560fad8d6eda7c5f0f9a7c2a7b4754ca701bac4b2f66f7e
